use_frameworks!

target 'AudiomackSwiftLibrary_Example' do
  pod 'AudiomackSwiftLibrary', :path => '../'
  pod 'FTIndicator'

  target 'AudiomackSwiftLibrary_Tests' do
    inherit! :search_paths

    
  end
end
